FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o myapp main.go

FROM alpine:3.19

RUN apk add --no-cache libc6-compat gcc g++ libc-dev musl-dev

# Copy the binary from the builder stage
COPY --from=builder /app/myapp /app/myapp

RUN chmod +x /app/myapp

WORKDIR /app

EXPOSE 8080

CMD ["./myapp"]


