FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/swaggo/swag/cmd/swag@latest

RUN swag init

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o uresport-api main.go

# Utilisez une image Alpine pour le runtime
FROM alpine:3.20

RUN apk add --no-cache libc6-compat gcc g++ libc-dev musl-dev

COPY --from=builder /app/uresport-api /app/uresport-api

RUN chmod +x /app/uresport-api

WORKDIR /app

EXPOSE 8080

CMD ["./uresport-api"]
