FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o myapp

FROM alpine:3.19

COPY --from=builder /app/myapp /app/myapp

WORKDIR /app

EXPOSE 8080

CMD ["./myapp"]
