#!/bin/sh
cat <<EOF > /app/.env
DB_HOST=$DB_HOST
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME
DB_PORT=$DB_PORT
COOKIE_SECURE=$COOKIE_SECURE
JWT_SECRET_KEY=$JWT_SECRET_KEY
BREVO_API_KEY=$BREVO_API_KEY
BREVO_SENDER=$BREVO_SENDER
EOF