# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
 desc "Deploy beta version to TestFlight"
 lane :deploy_beta_to_testflight do
    # Fetch the latest code signing certificates
    match(type: "appstore")

    # Increment the build number for beta deployments
    increment_build_number(
      xcodeproj: "ios/Runner.xcodeproj"
    )

    # Build your Flutter app for iOS
    flutter_build_ios(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      clean: true
    )

    # Upload the build to TestFlight
    upload_to_testflight
 end

 desc "Deploy production version to App Store"
 lane :deploy_to_app_store do
    # Fetch the latest code signing certificates
    match(type: "appstore")

    increment_build_number(
      xcodeproj: "ios/Runner.xcodeproj"
    )

    # Build your Flutter app for iOS
    flutter_build_ios(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      clean: true
    )

    # Upload the build to the App Store
    upload_to_app_store
 end
end
