name: uresport
description: "Beautify your Esport experience with Uresport"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  web_socket_channel: ^3.0.0
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  flutter_web_auth_2: ^3.1.2
  image_picker: ^1.1.2
  flutter_local_notifications: ^9.1.5
  overlay_support: ^1.2.1
  google_maps_flutter: ^2.7.0
  tournament_bracket: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^5.5.0+1
  intl_translation: ^0.20.0
  intl_utils: ^2.8.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated/l10n
