name: autofix.ci

on:
  pull_request:
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Autofix
        uses: autofix-ci/action@ea32e3a12414e6d3183163c3424a7d7a8631ad84