name: autofix.ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "front/**"
      - ".github/workflows/ci-front.yaml"

jobs:
  ci-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout
        uses: actions/checkout@v4
