name: autofix.ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "back/**"
      - ".github/workflows/ci-back.yaml"
permissions:
  contents: read

jobs:
  autofix-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
          cache: true
          cache-dependency-path: "**/go.sum"

      - name: Install dependencies
        run: go mod download

      - name: Install goImports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Format and Check Imports
        run: goimports -w .

      - name: Clean
        run: go mod tidy

      - name: format
        run: go fmt ./...

      - name: Autofix
        uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c