name: CI for Backend

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "back/**"
      - ".github/workflows/ci-back.yaml"

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  ci-back:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.22.0']
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: "**/go.sum"

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          args: --timeout=5m
          version: v1.54
          working-directory: back

      - name: Install Dependencies
        run: go mod download

      - name: Install goImports
        run: |
            go install golang.org/x/tools/cmd/goimports@latest
            echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Format and Check Imports
        run: goimports -w .

      - name: Build
        run: go build -v ./...

      - name: Test with Coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests-back
          slug: Pietrucci-Blacher/Challenge-Stack-2-5IW
          fail_ci_if_error: true
          verbose: true

      - name: Check for unused dependencies
        run: go mod tidy