  name: CI for Backend

  on:
    pull_request:
      types: [opened, synchronize, reopened]
      paths:
        - "back/**"
        - ".github/workflows/ci-back.yaml"

  permissions:
    contents: read
    pull-requests: read
    checks: write

  jobs:
    ci-back:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: back

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.22.2
            cache: true
            cache-dependency-path: "**/go.sum"

        - name: Install swaggo
          run: |
            go install github.com/swaggo/swag/cmd/swag@latest
            echo "$GOPATH/bin" >> $GITHUB_PATH

        - name : Generate Swagger
          run: swag init

        - name: Lint
          uses: golangci/golangci-lint-action@v5
          with:
            args: --timeout=5m
            version: v1.57
            working-directory: back

        - name: Install Dependencies
          run: go mod download

        - name: Check for unused dependencies
          run: go mod tidy

        - name: Install goImports
          run: |
              go install golang.org/x/tools/cmd/goimports@latest

        - name: Format and Check Imports
          run: goimports -w .

        - name: Build
          run: go build -v ./...

        - name: Run tests
          run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

        - name: Upload to Codecov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            file: ./cover.out
            flags: unittests-back
            slug: Pietrucci-Blacher/Challenge-Stack-2-5IW
            fail_ci_if_error: true
            verbose: true
