on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "back/**"
      - ".github/workflows/ci-back.yaml"

jobs:
  ci-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v4
