on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "front/**"
      - ".github/workflows/ci-front.yaml"

env:
  FLUTTER_CHANNEL: stable
  CACHE_VERSION: v1

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      flutter-version: ${{ steps.flutter-setup.outputs.flutter-version }}
      cache-key: ${{ steps.flutter-setup.outputs.cache-key }}
      cache-path: ${{ steps.flutter-setup.outputs.cache-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        id: flutter-setup
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: 'flutter-${{ runner.os }}-${{ env.FLUTTER_CHANNEL }}-${{ env.CACHE_VERSION }}'
          cache-path: '${{ runner.tool_cache }}/flutter/${{ env.FLUTTER_CHANNEL }}'

  test-and-build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [web, android, ios]
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Flutter from Cache
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.cache-path }}
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Set Flutter PATH
        run: echo "${{ needs.setup.outputs.cache-path }}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests and generate coverage report
        run: flutter test --coverage

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unittests
          slug: Pietrucci-Blacher/Challenge-Stack-2-5IW
          fail_ci_if_error: true
          verbose: true

      - name: Run static analysis
        run: flutter analyze

      - name: Build for ${{ matrix.platform }}
        run: |
          flutter build ${{ matrix.platform }}
